package DepartmentStore.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new AbstractDepartment_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Cinema_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ClothingStore_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new DepartmentStore_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Foodcourt_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Restaurant_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efa55L), MetaIdFactory.conceptId(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e808f7aL), MetaIdFactory.conceptId(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efa7eL), MetaIdFactory.conceptId(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x1056bad9babcf093L), MetaIdFactory.conceptId(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efabbL), MetaIdFactory.conceptId(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e85fa5dL)).seal();
}
