package DepartmentStore.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_clothingsType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_clothingsType() {
    super(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efad5L, "clothingsType", "r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210901");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_menClothings_0 = new EnumerationDescriptor.MemberDescriptor("menClothings", "menClothings", 0x5eeaac0b2e7efad6L, "r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210902");
  private final EnumerationDescriptor.MemberDescriptor myMember_womenClothings_0 = new EnumerationDescriptor.MemberDescriptor("womenClothings", "womenClothings", 0x5eeaac0b2e7efad7L, "r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210903");
  private final EnumerationDescriptor.MemberDescriptor myMember_kidsClothings_0 = new EnumerationDescriptor.MemberDescriptor("kidsClothings", "kidsClothings", 0x5eeaac0b2e7efadaL, "r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210906");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efad5L, 0x5eeaac0b2e7efad6L, 0x5eeaac0b2e7efad7L, 0x5eeaac0b2e7efadaL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_menClothings_0, myMember_womenClothings_0, myMember_kidsClothings_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "menClothings":
        return myMember_menClothings_0;
      case "womenClothings":
        return myMember_womenClothings_0;
      case "kidsClothings":
        return myMember_kidsClothings_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
