package DepartmentStore.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_foodType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_foodType() {
    super(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efadeL, "foodType", "r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210910");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_japanese_0 = new EnumerationDescriptor.MemberDescriptor("japanese", "japanese", 0x5eeaac0b2e7efadfL, "r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210911");
  private final EnumerationDescriptor.MemberDescriptor myMember_italian_0 = new EnumerationDescriptor.MemberDescriptor("italian", "italian", 0x5eeaac0b2e7efae0L, "r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210912");
  private final EnumerationDescriptor.MemberDescriptor myMember_fastFood_0 = new EnumerationDescriptor.MemberDescriptor("fastFood", "fastFood", 0x5eeaac0b2e7efae7L, "r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210919");
  private final EnumerationDescriptor.MemberDescriptor myMember_cafe_0 = new EnumerationDescriptor.MemberDescriptor("cafe", "cafe", 0x5eeaac0b2e7efae3L, "r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210915");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efadeL, 0x5eeaac0b2e7efadfL, 0x5eeaac0b2e7efae0L, 0x5eeaac0b2e7efae7L, 0x5eeaac0b2e7efae3L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_japanese_0, myMember_italian_0, myMember_fastFood_0, myMember_cafe_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "japanese":
        return myMember_japanese_0;
      case "italian":
        return myMember_italian_0;
      case "fastFood":
        return myMember_fastFood_0;
      case "cafe":
        return myMember_cafe_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
