package DepartmentStore.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AbstractDepartment = 0;
  public static final int Cinema = 1;
  public static final int ClothingStore = 2;
  public static final int DepartmentStore = 3;
  public static final int Foodcourt = 4;
  public static final int Restaurant = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L);
    builder.put(0x5eeaac0b2e7efa55L, AbstractDepartment);
    builder.put(0x5eeaac0b2e808f7aL, Cinema);
    builder.put(0x5eeaac0b2e7efa7eL, ClothingStore);
    builder.put(0x1056bad9babcf093L, DepartmentStore);
    builder.put(0x5eeaac0b2e7efabbL, Foodcourt);
    builder.put(0x5eeaac0b2e85fa5dL, Restaurant);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
