package DepartmentStore.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAbstractDepartment = createDescriptorForAbstractDepartment();
  /*package*/ final ConceptDescriptor myConceptCinema = createDescriptorForCinema();
  /*package*/ final ConceptDescriptor myConceptClothingStore = createDescriptorForClothingStore();
  /*package*/ final ConceptDescriptor myConceptDepartmentStore = createDescriptorForDepartmentStore();
  /*package*/ final ConceptDescriptor myConceptFoodcourt = createDescriptorForFoodcourt();
  /*package*/ final ConceptDescriptor myConceptRestaurant = createDescriptorForRestaurant();
  /*package*/ final EnumerationDescriptor myEnumerationclothingsType = new EnumerationDescriptor_clothingsType();
  /*package*/ final EnumerationDescriptor myEnumerationfoodType = new EnumerationDescriptor_foodType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAbstractDepartment, myConceptCinema, myConceptClothingStore, myConceptDepartmentStore, myConceptFoodcourt, myConceptRestaurant);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AbstractDepartment:
        return myConceptAbstractDepartment;
      case LanguageConceptSwitch.Cinema:
        return myConceptCinema;
      case LanguageConceptSwitch.ClothingStore:
        return myConceptClothingStore;
      case LanguageConceptSwitch.DepartmentStore:
        return myConceptDepartmentStore;
      case LanguageConceptSwitch.Foodcourt:
        return myConceptFoodcourt;
      case LanguageConceptSwitch.Restaurant:
        return myConceptRestaurant;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationclothingsType, myEnumerationfoodType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAbstractDepartment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DepartmentStore", "AbstractDepartment", 0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efa55L);
    b.class_(false, false, false);
    b.origin("r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210773");
    b.version(2);
    b.property("managerAmount", 0x5eeaac0b2e7efa56L).type(PrimitiveTypeId.INTEGER).origin("6839468148140210774").done();
    b.property("employeeAmount", 0x5eeaac0b2e7efa5bL).type(PrimitiveTypeId.INTEGER).origin("6839468148140210779").done();
    b.property("capacity", 0x5eeaac0b2e7efa81L).type(PrimitiveTypeId.INTEGER).origin("6839468148140210817").done();
    b.aggregate("foodcort", 0x5eeaac0b2e808fafL).target(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efabbL).optional(true).ordered(true).multiple(false).origin("6839468148140314543").done();
    b.aggregate("cinema", 0x5eeaac0b2e808fb3L).target(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e808f7aL).optional(true).ordered(true).multiple(false).origin("6839468148140314547").done();
    b.aggregate("clothingStores", 0x5eeaac0b2e808fb6L).target(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efa7eL).optional(true).ordered(true).multiple(true).origin("6839468148140314550").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCinema() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DepartmentStore", "Cinema", 0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e808f7aL);
    b.class_(false, false, false);
    b.super_("DepartmentStore.structure.AbstractDepartment", 0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efa55L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140314490");
    b.version(2);
    b.property("floorNumber", 0x5eeaac0b2e80aeb3L).type(PrimitiveTypeId.INTEGER).origin("6839468148140322483").done();
    b.property("theatherAmount", 0x5eeaac0b2e808f7dL).type(PrimitiveTypeId.INTEGER).origin("6839468148140314493").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClothingStore() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DepartmentStore", "ClothingStore", 0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efa7eL);
    b.class_(false, false, false);
    b.super_("DepartmentStore.structure.AbstractDepartment", 0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efa55L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210814");
    b.version(2);
    b.property("floorNumber", 0x5eeaac0b2e80aeb7L).type(PrimitiveTypeId.INTEGER).origin("6839468148140322487").done();
    b.property("type", 0x5eeaac0b2e7efa7fL).type(MetaIdFactory.dataTypeId(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efad5L)).origin("6839468148140210815").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDepartmentStore() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DepartmentStore", "DepartmentStore", 0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x1056bad9babcf093L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/1177333796907577491");
    b.version(2);
    b.property("location", 0x5eeaac0b2e7efa4aL).type(PrimitiveTypeId.STRING).origin("6839468148140210762").done();
    b.property("owner", 0x5eeaac0b2e806968L).type(PrimitiveTypeId.STRING).origin("6839468148140304744").done();
    b.aggregate("departments", 0x5eeaac0b2e7fb221L).target(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efa55L).optional(false).ordered(true).multiple(false).origin("6839468148140257825").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFoodcourt() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DepartmentStore", "Foodcourt", 0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efabbL);
    b.class_(false, false, false);
    b.super_("DepartmentStore.structure.AbstractDepartment", 0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efa55L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140210875");
    b.version(2);
    b.property("floorNumber", 0x5eeaac0b2e80aeaeL).type(PrimitiveTypeId.INTEGER).origin("6839468148140322478").done();
    b.aggregate("restaurants", 0x5eeaac0b2e85fa5aL).target(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e85fa5dL).optional(false).ordered(true).multiple(true).origin("6839468148140669530").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRestaurant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DepartmentStore", "Restaurant", 0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e85fa5dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b082e190-2d1c-4660-93cd-05be5a093c1b(DepartmentStore.structure)/6839468148140669533");
    b.version(2);
    b.property("type", 0x5eeaac0b2e85fa5eL).type(MetaIdFactory.dataTypeId(0xad996c65d1384f51L, 0x97d767bdd4bb8c81L, 0x5eeaac0b2e7efadeL)).origin("6839468148140669534").done();
    return b.create();
  }
}
